apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: viken-no

resources:
  - ../../../base
  - acos-oauth2-client.yaml

commonLabels:
  app.kubernetes.io/instance: fint-flyt-authorization-service_viken_no
  fintlabs.no/org-id: viken.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "viken-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "viken.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "viken.no, vigo.no"
      - op: replace
        path: "/spec/onePassword"
        value: null

    target:
      kind: Application
      name: fint-flyt-authorization-service