apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vestfoldfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-authorization-service_vestfoldfylke_no
      fintlabs.no/org-id: vestfoldfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vestfoldfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vestfoldfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/vestfoldfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/vestfoldfylke-no/api/intern/authorization"
      - op: replace
        path: "/spec/env/1/value"
        value: |
          {
            "vestfoldfylke.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
      - op: replace
        path: "/spec/probes/readiness/path"
        value: "/beta/vestfoldfylke-no/actuator/health"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/beta/vestfoldfylke-no/actuator/prometheus"
    target:
      kind: Application
      name: fint-flyt-authorization-service

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-altinn-oauth2-client"
    target:
      kind: OnePasswordItem
      name: fint-flyt-altinn-oauth2-client

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-egrunnerverv-oauth2-client"
    target:
      kind: OnePasswordItem
      name: fint-flyt-egrunnerverv-oauth2-client