azure:
  credentials:
    clientid: ${fint.flyt.azure.client-id}
    clientsecret: ${fint.flyt.azure.client-secret}
    tenantid: ${fint.flyt.azure.tenant-id}
    appid: ${fint.flyt.azure.app-id}

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${azure.credentials.clientid}
            client-secret: ${azure.credentials.clientsecret}
            authorization-grant-type: client_credentials
            scope: "https://graph.microsoft.com/.default"
        provider:
          azure:
            authorization-uri: "https://login.microsoftonline.com/${azure.credentials.tenantid}/oauth2/v2.0/authorize"
            token-uri: "https://login.microsoftonline.com/${azure.credentials.tenantid}/oauth2/v2.0/token"

fint:
  flyt:
    azure-ad-gateway:
      approles:
        flyt-user: "https://role-catalog.vigoiks.no/vigo/flyt/user"
        flyt-developer: "https://role-catalog.vigoiks.no/vigo/flyt/developer"
        flyt-admin: "https://role-catalog.vigoiks.no/vigo/flyt/developer"
      user-scheduler:
        pull:
          initial-delay-ms: 1000
          fixed-delay-ms: 600000