apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: fint-flyt-digisak-oauth2-client
  namespace: vlfk-no
spec:
  itemPath: "vaults/aks-beta-vault/items/fint-flyt-digisak-oauth2-client-vlfk-no"
