apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemarkfylke-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-authorization-telemarkfylke_no
  fintlabs.no/org-id: telemarkfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "telemarkfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "telemarkfylke.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "telemarkfylke.no, vigo.no"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-api-vault/items/fint-flyt-egrunnerverv-oauth2-client"
    target:
      kind: Application
      name: fint-flyt-authorization-service