apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telemarkfylke-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-authorization-telemarkfylke_no
  fintlabs.no/org-id: telemarkfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "telemarkfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "telemarkfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/telemarkfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/telemarkfylke-no/api/intern/authorization"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-api-vault/items/fint-flyt-egrunnerverv-oauth2-client"
      - op: replace
        path: "/spec/env/1/value"
        value: |
          {
            "telemarkfylke.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
      - op: add
        path: "/spec/envFrom/0"
        value:
          secretRef:
            name: fint-flyt-authorization-service
    target:
      kind: Application
      name: fint-flyt-authorization-service
  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/telemarkfylke-no/items/FINT-Flyt-Role-TelemarkFK"
    target:
      kind: OnePasswordItem
      name: fint-flyt-authorization-service