apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vlfk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-authorization-service_vlfk_no
  fintlabs.no/org-id: vlfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vlfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vlfk.no"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-api-vault/items/fint-flyt-egrunnerverv-oauth2-client"
      - op: replace
        path: "/spec/env/1/value"
        value: |
          {
            "vlfk.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
    target:
      kind: Application
      name: fint-flyt-authorization-service