apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-authorization-service_nfk_no
  fintlabs.no/org-id: nfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "nfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "nfk.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "nfk.no, vigo.no"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-egrunnerverv-oauth2-client"
    target:
      kind: Application
      name: fint-flyt-authorization-service