apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-authorization-service_fintlabs_no
  fintlabs.no/org-id: fintlabs.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fintlabs-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "fintlabs.no, vigo.no"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-alpha-vault/items/fint-flyt-egrunnerverv-oauth2-client"
    target:
      kind: Application
      name: fint-flyt-authorization-service