apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ffk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-authorization-service_ffk_no
  fintlabs.no/org-id: ffk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "ffk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "ffk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/ffk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/ffk-no/api/intern/authorization"
      - op: replace
        path: "/spec/env/1/value"
        value: |
          {
            "ffk.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
    target:
      kind: Application
      name: fint-flyt-authorization-service

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-altinn-oauth2-client"
    target:
      kind: OnePasswordItem
      name: fint-flyt-altinn-oauth2-client

  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/fint-flyt-egrunnerverv-oauth2-client"
    target:
      kind: OnePasswordItem
      name: fint-flyt-egrunnerverv-oauth2-client