create table revinfo
(
    rev      integer generated by default as identity not null,
    revtstmp bigint                                  not null,
    actor    varchar(255)                            not null,
    primary key (rev)
);

create table user_entity_aud
(
    rev               integer not null,
    revtype           smallint,
    id                bigint  not null,
    email             varchar(255),
    name              varchar(255),
    object_identifier uuid,
    primary key (rev, id)
);

create table user_entity_source_application_ids_aud
(
    rev                    integer not null,
    revtype                smallint,
    user_entity_id         bigint  not null,
    source_application_ids bigint  not null,
    primary key (rev, user_entity_id, source_application_ids)
);

alter table user_entity_aud
    add constraint FK_user_entity_aud_rev foreign key (rev) references revinfo;

alter table user_entity_source_application_ids_aud
    add constraint FK_user_entity_source_application_ids_aud_rev foreign key (rev) references revinfo;

create index IDX_user_entity_aud_id on user_entity_aud (id);

create index IDX_user_entity_source_application_ids_aud_user_entity_id
    on user_entity_source_application_ids_aud (user_entity_id);
